### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by adityatelange** [rahulsekar/brautopy#1]
PS C:\Users\adity\Desktop\brautopy-master> python server.py
Traceback (most recent call last):
  File "server.py", line 9, in <module>
    from opus.decoder import Decoder as OpusDecoder
  File "C:\Users\adity\Desktop\brautopy-master\opus\decoder.py", line 3, in <module>
    from opus.api import decoder, ctl
  File "C:\Users\adity\Desktop\brautopy-master\opus\api\decoder.py", line 6, in <module>
    from opus.api import libopus, c_int_pointer, c_int16_pointer, c_float_pointer
ImportError: cannot import name 'libopus'

This is what im getting, 
running on Windows-10 machine

**Comment by rahulsekar** [comment]
@AdityaTelange Thanks for reporting. libopus has to be installed separately for windows. I have updated the readme but I don't have a windows machine to check. Let me know if it doesn't work.

Also cleaned up the requirements & python3.6 is now recommended.
